### ISSUE TITLE
Configuration Questions

### ISSUE THREAD

**Issue by Jagestah** [electrode-io/electrode-ota-server#89]
I'm a DevOps guy who's been tasked with building a self-hosted CodePush-esque server and Electrode OTA is the solution we're looking at now. I don't have much experience with the tools used in this project so I'll be relying heavily on the team who built it to tell me if something is or isn't possible, and ultimately some guidance on how to build it. Below I have a list of the Specs we're looking for.

Could I get some feedback on the feasibility of these specs and the compromises I might have to make to achieve the goal?

#### Goals
- Deploy Electrode OTA Server to a development and then production cluster of Kubernetes on AWS
#### Specs
- Containerized with Docker
- List of required environment variables
- List of required ports/protocols
- All Requirements also Containerized with Docker
- Use Auth0 to get authorization tokens
- Serve files directly from the filesystem of the OTA Server container, rather than an external DB.

**Comment by datvong-wm** [comment]
More info here: http://www.electrode.io/docs/electrode_react_native_over_the_air_electron.html


- Containerized with Docker
haven't tried, but should be doable.  just a NodeJS app with associated DB.

- List of required environment variables
NODE_ENV and NODE_APP_INSTANCE for loading the appropriate config (https://github.com/electrode-io/electrode-confippet#config-composition)

- List of required ports/protocols
80/HTTP
443/HTTPS
mariadb port
or cassandra port if using cassandra

- All Requirements also Containerized with Docker
app container
db container
connectivity between containers
opening http/https ports

- Use Auth0 to get authorization tokens
https://docs.electrode.io/other/powerful-electrode-tools/react-native-and-over-the-air#setting-up-oauth

- Serve files directly from the filesystem of the OTA Server container, rather than an external DB
It's designed to store in the DB.  You would have to write custom overrides for modules `electrode-ota-server-fileservice-download` and `electrode-ota-server-fileservice-upload` to download/upload from/to filesystem.

**Comment by datvong-wm** [comment]
If you use MariaDB, then a docker-compose already exists for the database.  https://github.com/electrode-io/electrode-ota-server/tree/master/electrode-ota-mariadb-schema
